indent = 4
margin = 100
always_for_in = true
for_in_replacement = "∈"
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = false
normalize_line_endings = "unix"
