name: Documentation

on:
  push:
    branches: [ main ]
    tags: "v?[0-9]+.[0-9]+.[0-9]+**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
  contents: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: '1'
      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # v3.1.0
      - name: Configure doc environment
        shell: julia --project=docs --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1.7.0
      - uses: julia-actions/julia-docdeploy@e62cc8fd639797a0c2922a437d5b1b81c4a12787 # v1.3.1
        env:
          G.7.0ITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          D.7.0OCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - name: Run doctests
        shell: julia --project=docs --color=yes {0}
        run: |
          using Documenter: DocMeta, doctest
          using Muon
          DocMeta.setdocmeta!(Muon, :DocTestSetup, :(using Muon); recursive=true)
          doctest(Muon)
